version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/node-express-realworld-example-app


hooks:
   ApplicationStop:
         - location: /script/stop_script.sh
           timeout: 300
           runas: root

   ApplicationStart:
         - location: /script/start_script.sh
           timeout: 300
           runas: root 
